### ISSUE TITLE
Only use class with composes

### ISSUE THREAD

**Issue by eddiemoore** [atfzl/eslint-plugin-css-modules#13]
If you only use a class that is composing from another class within the same file it will say that the composed class is unused.
```css
.round {
  border-radius: 50%;
}

.myThing {
  composes: round;
  background-color: red;
}
```

In this case if I only use `.myThing` in a component, the plugin will say that `.round` is never used.
Hope that makes sense.

**Comment by atfzl** [comment]
Hi @eddiemoore,

You have you add a trailing `.` before the classname while using `composes`, like this:

```css
.myThing {
  composes: .round;
  background-color: red;
}
```
