### ISSUE TITLE
no-undef-class with :global

### ISSUE THREAD

**Issue by eddiemoore** [atfzl/eslint-plugin-css-modules#14]
If you have a global class that you only want something applied when it is a child of another class.
```css
/* fails */
.holder :global .Select {}
```

If `.holder` doesn't have a class of it's own, it says that `.holder` is unused. To get it to pass we need to change `.holder` to have css applied otherwise it has an error of `no-undef-class` with `.holder`

```css
/* passes */
.holder { display: block; }
.holder :global .Select {}
```
