### ISSUE TITLE
no-undef-class for "pseudo-nested" classes and classes from @import files

### ISSUE THREAD

**Issue by nelsonleite** [atfzl/eslint-plugin-css-modules#15]
I'm using PostCSS, and if you have some kind of nesting, it throws a false `no-undef-class`. Take this example:

```jsx
<div className={ styles['container-green'] }>
    This container is green
</div>

<div className={ `${styles.container} ${styles.isLoading}` }>
    This container is green
</div>
```

```css
.container {
    &-green {
        background-color: green;
    }

    &.isLoading {
        background-color: grey;
    }
}
```

The linter does not recognise `.container-green` nor `.container.isLoading`, even though they exist.

***

Also, if I'm importing a file with a given class and use it in my component, it throws again `no-undef-class`. This might be an non issue, but I report it anyway. Take this example:

**styles.css**

```css
.container-green {
     background-color: green;
}
```

**component.css**

```css
@import 'styles.css';

...
```

**component.js**

```html
<div className={ s['container-green'] }>
    This container is green
</div>
```

In this case `container-green` is not recognised as well.
