### ISSUE TITLE
Linting hangs when using parenthesis in calc

### ISSUE THREAD

**Issue by gdub22** [atfzl/eslint-plugin-css-modules#16]
Hangs:
```css
.foo {
  width: calc(100% - (20px * 2));
}
```
OK:
```css
.foo {
  width: calc(100% - 20px * 2);
}
```
