### ISSUE TITLE
Support dynamic object keys

### ISSUE THREAD

**Issue by pascalduez** [atfzl/eslint-plugin-css-modules#2]
Hi,

there's a quite common pattern which is not supported at the moment.
Accessing the styles object values with dynamic keys (variables).

```js
import React, { PropTypes } from 'react';
import styles from './Button.css';

const Button = ({ theme }) => (
  <button className={styles[theme]} />
);

Button.propTypes = {
  theme: PropTypes.oneOf(['primary', 'secondary', 'danger']),
};

Button.defaultProps = {
  theme: 'primary',
};
```
```css
.primary {
  color: green;
}

.secondary {
  color: blue;
}

.danger {
  color: red;
}
```

Results in:
```
css-modules/no-undef-class Class 'theme' not found at line ...
css-modules/no-unused-class Unused classes found: primary, secondary, danger at line ...
```
