### ISSUE TITLE
css-modules/no-undef-class error 

### ISSUE THREAD

**Issue by talentedandrew** [atfzl/eslint-plugin-css-modules#38]
I'm getting this error `error  Class 'container' not found  css-modules/no-undef-class` for the below scenario.

**Home.js**
```js
import React from 'react';
import PropTypes from 'prop-types';
import s from './Home.scss';
class Home extends React.Component {
  render() {
    return (
      <div className={s.root}>
        <div className={s.container}>
          <h1>Soome Other Name</h1>
        </div>
      </div>
    );
  }
}
```
`Home.scss`

```scss
@import './commoncss.scss';

.root {
  padding-left: 20px;
  padding-right: 20px;
}

```

`commoncss.scss`

```scss
.container {
  margin: 0 auto;
  padding: 0 0 40px;
}
```
