### ISSUE TITLE
False negative with :not

### ISSUE THREAD

**Issue by amannn** [atfzl/eslint-plugin-css-modules#48]
SCSS:
```scss
.root {
  &:not(.selected) {
    opacity: 0.5;
  }
}
```

JS:
```jsx
<div className={cx(styles.root, styles.selected)} />
```
